// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TBSAnalytics.Models;

namespace TBSAnalytics.Migrations
{
    [DbContext(typeof(TBSContext))]
    [Migration("20210610132724_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TBSAnalytics.Models.Branch", b =>
                {
                    b.Property<string>("BrcCode")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("BrcName")
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("BrcRegion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BrcStatus")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BrcCode");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            BrcCode = "01",
                            BrcName = "Gefinor Branch",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "02",
                            BrcName = "JAL EL DIB",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "03",
                            BrcName = "MAR ELIAS",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "04",
                            BrcName = "BROUMANA",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "05",
                            BrcName = "HAZMIEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "06",
                            BrcName = "NAHR",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "07",
                            BrcName = "JOUNIEH",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "08",
                            BrcName = "SIN EL FIL",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "09",
                            BrcName = "TARIK EL JDIDEH",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "10",
                            BrcName = "BAUCHRIEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "11",
                            BrcName = "ACHRAFIEH - SIOUFI",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "13",
                            BrcName = "ANTELIAS",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "14",
                            BrcName = "CHIAH",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "15",
                            BrcName = "JDEIDEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "16",
                            BrcName = "BOURJ HAMMOUD",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "17",
                            BrcName = "RAS BEIRUT",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "18",
                            BrcName = "HORCH TABET",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "19",
                            BrcName = "ACHRAFIEH - SAYDEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "22",
                            BrcName = "MAZRAAT YACHOUH - ELYSSAR",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "24",
                            BrcName = "KFARSAROUN",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "25",
                            BrcName = "JAL EL DIB SQUARE",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "26",
                            BrcName = "JOUNIEH - GHADIR",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "27",
                            BrcName = "MANSOURIEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "28",
                            BrcName = "SOUR",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "29",
                            BrcName = "AIN EL REMMANEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "30",
                            BrcName = "SAIDA",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "31",
                            BrcName = "MAZRAA - BARBIR               ",
                            BrcRegion = "WEST",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "32",
                            BrcName = "KORAYTEM",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "33",
                            BrcName = "FOCH",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "34",
                            BrcName = "RIYAD EL SOLH",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "35",
                            BrcName = "MAZRAA",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "36",
                            BrcName = "HAMRA",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "37",
                            BrcName = "GHOBEIRY AIRPORT ROAD",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "38",
                            BrcName = "PALAIS DE JUSTICE",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "39",
                            BrcName = "DORA",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "41",
                            BrcName = "TYR-AL RAML",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "42",
                            BrcName = "JBEIL",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "43",
                            BrcName = "TRIPOLI-BANKS STREET",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "44",
                            BrcName = "ALEY",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "45",
                            BrcName = "CHTAURA",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "47",
                            BrcName = "TRIPOLI ABOU SAMRA            ",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "48",
                            BrcName = "ZOUK MOSBEH",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "49",
                            BrcName = "KASLIK",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "50",
                            BrcName = "FEYTROUN",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "51",
                            BrcName = "SIDANI",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "52",
                            BrcName = "BEIRUT PORT",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "53",
                            BrcName = "CORNICHE EL-MAZRAA",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "54",
                            BrcName = "BEIT EL CHAAR-AOUKAR",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "55",
                            BrcName = "DEKWANEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "56",
                            BrcName = "DHOUR EL-CHOUEIR",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "57",
                            BrcName = "RABIEH",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "58",
                            BrcName = "AMCHIT",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "59",
                            BrcName = "GHAZIR",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "60",
                            BrcName = "BASKINTA",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "61",
                            BrcName = "CHEHABIYEH",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "62",
                            BrcName = "ZOUK MICHAEL",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "63",
                            BrcName = "DEIR EL ZAHRANI",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "64",
                            BrcName = "BALLOUNEH",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "65",
                            BrcName = "BAYADA-CORNET CHAHWAN",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "66",
                            BrcName = "SADAT",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "67",
                            BrcName = "JBEIL - VOIE 13",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "68",
                            BrcName = "ACHRAFIEH-ATAYA",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "69",
                            BrcName = "BATROUN",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "70",
                            BrcName = "BAABDA",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "71",
                            BrcName = "CHOUEIFAT",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "72",
                            BrcName = "FARAYA",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "73",
                            BrcName = "ACHKOUT",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "74",
                            BrcName = "SIN EL FIL-HAYEK",
                            BrcRegion = "East",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "75",
                            BrcName = "BCHARRE",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "76",
                            BrcName = "ZAHLE",
                            BrcRegion = "West",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "77",
                            BrcName = "CASINO BRANCH",
                            BrcRegion = "North",
                            BrcStatus = "Active"
                        },
                        new
                        {
                            BrcCode = "999",
                            BrcName = "NONE",
                            BrcRegion = "NONE",
                            BrcStatus = "Active"
                        });
                });

            modelBuilder.Entity("TBSAnalytics.Models.Customer", b =>
                {
                    b.Property<string>("CustId")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("BrcCode")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CustName")
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("CustStatus")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EcoSectId")
                        .HasColumnType("int");

                    b.Property<bool>("Enrolled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EnrolledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RMSegment")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServicePackage")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustId");

                    b.HasIndex("BrcCode");

                    b.HasIndex("EcoSectId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustId = "006066",
                            BrcCode = "15",
                            CustName = "NAUFAL GROUP S.A.R.L.",
                            CustStatus = "Active",
                            CustType = "Corporate",
                            EcoSectId = 1,
                            Enrolled = true,
                            EnrolledDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OpenDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RMSegment = "MMD",
                            ServicePackage = "Information Only"
                        },
                        new
                        {
                            CustId = "009680",
                            BrcCode = "48",
                            CustName = "COMPUTER & COMMUNICATIONSSYSTEMS INC.",
                            CustStatus = "Active",
                            CustType = "Corporate",
                            EcoSectId = 2,
                            Enrolled = true,
                            EnrolledDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OpenDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RMSegment = "BBU",
                            ServicePackage = "All Services Admin"
                        },
                        new
                        {
                            CustId = "009330",
                            BrcCode = "74",
                            CustName = "MDS EAST EUROPE LTD",
                            CustStatus = "Active",
                            CustType = "Corporate",
                            EcoSectId = 3,
                            Enrolled = true,
                            EnrolledDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OpenDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RMSegment = "CBD",
                            ServicePackage = "All Services User"
                        },
                        new
                        {
                            CustId = "600055",
                            BrcCode = "74",
                            CustName = "Osmat Ayash",
                            CustStatus = "Active",
                            CustType = "Establishment",
                            EcoSectId = 3,
                            Enrolled = false,
                            EnrolledDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OpenDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RMSegment = "",
                            ServicePackage = ""
                        },
                        new
                        {
                            CustId = "009744",
                            BrcCode = "33",
                            CustName = "AOUT PLUS SAL. AL",
                            CustStatus = "Active",
                            CustType = "Establishment",
                            EcoSectId = 1,
                            Enrolled = true,
                            EnrolledDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OpenDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            RMSegment = "BBU",
                            ServicePackage = "Information Only"
                        });
                });

            modelBuilder.Entity("TBSAnalytics.Models.EcoSector", b =>
                {
                    b.Property<int>("EcoSectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EcoSectDesc")
                        .HasColumnType("nvarchar(225)");

                    b.HasKey("EcoSectId");

                    b.ToTable("EcoSector");

                    b.HasData(
                        new
                        {
                            EcoSectId = 1,
                            EcoSectDesc = "Consultancy Services"
                        },
                        new
                        {
                            EcoSectId = 2,
                            EcoSectDesc = "Travel Agency"
                        },
                        new
                        {
                            EcoSectId = 3,
                            EcoSectDesc = "Information Technology (IT) Company"
                        },
                        new
                        {
                            EcoSectId = 4,
                            EcoSectDesc = "Pharmaceutical / Medical Products"
                        });
                });

            modelBuilder.Entity("TBSAnalytics.Models.Transaction", b =>
                {
                    b.Property<int>("TrxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CustId")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Narration1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Narration2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TrxAmount")
                        .HasColumnType("decimal(38,3)");

                    b.Property<decimal>("TrxAmountUsd")
                        .HasColumnType("decimal(38,3)");

                    b.Property<string>("TrxChannel")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrxCurrency")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("TrxDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrxTypeId")
                        .HasColumnType("int");

                    b.HasKey("TrxId");

                    b.HasIndex("CustId");

                    b.HasIndex("TrxTypeId");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            TrxId = 1,
                            AccountNumber = "1140200968000",
                            CustId = "009680",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 1
                        },
                        new
                        {
                            TrxId = 2,
                            AccountNumber = "1140200968000",
                            CustId = "009680",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 500m,
                            TrxAmountUsd = 700m,
                            TrxChannel = "MOB",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 3,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 4000m,
                            TrxAmountUsd = 4000m,
                            TrxChannel = "OLB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 4,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 5000m,
                            TrxAmountUsd = 5000m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 3
                        },
                        new
                        {
                            TrxId = 5,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "MOB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 4
                        },
                        new
                        {
                            TrxId = 6,
                            AccountNumber = "1140200933000",
                            CustId = "009330",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 500m,
                            TrxAmountUsd = 700m,
                            TrxChannel = "MOB",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 7,
                            AccountNumber = "1140200933000",
                            CustId = "009330",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 4000m,
                            TrxAmountUsd = 4000m,
                            TrxChannel = "OLB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 8,
                            AccountNumber = "1140200933000",
                            CustId = "009330",
                            Narration2 = "",
                            TrxAmount = 5000m,
                            TrxAmountUsd = 5000m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 3
                        },
                        new
                        {
                            TrxId = 9,
                            AccountNumber = "1140200974400",
                            CustId = "009744",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 600m,
                            TrxAmountUsd = 800m,
                            TrxChannel = "MOB",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 10,
                            AccountNumber = "1140200974400",
                            CustId = "009744",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 400m,
                            TrxAmountUsd = 400m,
                            TrxChannel = "BRC",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 1
                        },
                        new
                        {
                            TrxId = 11,
                            AccountNumber = "1140200974400",
                            CustId = "009744",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 900m,
                            TrxAmountUsd = 900m,
                            TrxChannel = "BRC",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 12,
                            AccountNumber = "1140200974400",
                            CustId = "009744",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 4500m,
                            TrxAmountUsd = 4500m,
                            TrxChannel = "OLB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 13,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 8500m,
                            TrxAmountUsd = 8500m,
                            TrxChannel = "BRC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 1
                        },
                        new
                        {
                            TrxId = 14,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "BRC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            TrxTypeId = 4
                        },
                        new
                        {
                            TrxId = 15,
                            AccountNumber = "1140200968000",
                            CustId = "009680",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 1
                        },
                        new
                        {
                            TrxId = 16,
                            AccountNumber = "1140200968000",
                            CustId = "009680",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 500m,
                            TrxAmountUsd = 700m,
                            TrxChannel = "MOB",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 17,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 4000m,
                            TrxAmountUsd = 4000m,
                            TrxChannel = "OLB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 18,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 5000m,
                            TrxAmountUsd = 5000m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 3
                        },
                        new
                        {
                            TrxId = 19,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "MOB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 4
                        },
                        new
                        {
                            TrxId = 20,
                            AccountNumber = "1140200968000",
                            CustId = "009680",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 1
                        },
                        new
                        {
                            TrxId = 21,
                            AccountNumber = "1140200968000",
                            CustId = "009680",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 500m,
                            TrxAmountUsd = 700m,
                            TrxChannel = "MOB",
                            TrxCurrency = "EUR",
                            TrxDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 22,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 4000m,
                            TrxAmountUsd = 4000m,
                            TrxChannel = "OLB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 2
                        },
                        new
                        {
                            TrxId = 23,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration1 = "Narration 1",
                            Narration2 = "",
                            TrxAmount = 5000m,
                            TrxAmountUsd = 5000m,
                            TrxChannel = "FCC",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 3
                        },
                        new
                        {
                            TrxId = 24,
                            AccountNumber = "1140200606600",
                            CustId = "006066",
                            Narration2 = "",
                            TrxAmount = 29991.29m,
                            TrxAmountUsd = 29991.29m,
                            TrxChannel = "MOB",
                            TrxCurrency = "USD",
                            TrxDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrxTypeId = 4
                        });
                });

            modelBuilder.Entity("TBSAnalytics.Models.TrxType", b =>
                {
                    b.Property<int>("TrxTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TrxTypeDesc")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TrxTypeId");

                    b.ToTable("TrxType");

                    b.HasData(
                        new
                        {
                            TrxTypeId = 1,
                            TrxTypeDesc = "Wires"
                        },
                        new
                        {
                            TrxTypeId = 2,
                            TrxTypeDesc = "Transfers"
                        },
                        new
                        {
                            TrxTypeId = 3,
                            TrxTypeDesc = "Demand Draft"
                        },
                        new
                        {
                            TrxTypeId = 4,
                            TrxTypeDesc = "Port Bills"
                        });
                });

            modelBuilder.Entity("TBSAnalytics.Models.Customer", b =>
                {
                    b.HasOne("TBSAnalytics.Models.Branch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BrcCode");

                    b.HasOne("TBSAnalytics.Models.EcoSector", "EcoSectors")
                        .WithMany("Customers")
                        .HasForeignKey("EcoSectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("EcoSectors");
                });

            modelBuilder.Entity("TBSAnalytics.Models.Transaction", b =>
                {
                    b.HasOne("TBSAnalytics.Models.Customer", "Customers")
                        .WithMany()
                        .HasForeignKey("CustId");

                    b.HasOne("TBSAnalytics.Models.TrxType", "TrxTypes")
                        .WithMany("Transactions")
                        .HasForeignKey("TrxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("TrxTypes");
                });

            modelBuilder.Entity("TBSAnalytics.Models.Branch", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TBSAnalytics.Models.EcoSector", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TBSAnalytics.Models.TrxType", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
